name: ASP.NET Core CI

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore .NET dependencies
      run: |
        dotnet restore "./Market.Api/Market.Api.csproj"
        dotnet restore "./Maroc.Core/Maroc.Core.csproj"
        dotnet restore "./Maroc.Infastructure/Maroc.Infastructure.csproj"

    - name: Build .NET projects
      run: |
        dotnet build "./Market.Api/Market.Api.csproj" --configuration Release --no-restore
        dotnet build "./Maroc.Core/Maroc.Core.csproj" --configuration Release --no-restore
        dotnet build "./Maroc.Infastructure/Maroc.Infastructure.csproj" --configuration Release --no-restore

    - name: Run .NET tests
      run: |
        dotnet test "./Market.Api/Market.Api.csproj" --no-restore --verbosity normal
        dotnet test "./Maroc.Core/Maroc.Core.csproj" --no-restore --verbosity normal
        dotnet test "./Maroc.Infastructure/Maroc.Infastructure.csproj" --no-restore --verbosity normal
        
    - name: Setup Node.js for React
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'  

    - name: Install React dependencies
      run: npm install --prefix marocmarketplace.react

    - name: Build React project
      run: npm run build --prefix marocmarketplace.react
