name: ASP.NET Core CI

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: List specific directory content
      run: ls -la Maroc.Api/

    - name: Restore .NET dependencies
      run: |
        dotnet restore "./Maroc.Api/Maroc.Api.csproj"
        dotnet restore "./Maroc.Core/Maroc.Core.csproj"
        dotnet restore "./Maroc.Infrastructure/Maroc.Infrastructure.csproj"
        
    - name: Setup Node.js for React
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'  

    - name: Install React dependencies
      run: npm install --prefix MarocMarketplace/marocmarketplace.react

    - name: Build React project
      run: npm run build --prefix MarocMarketplace/marocmarketplace.react

    - name: Build .NET projects
      run: |
        dotnet build "MarocMarketplace/Maroc.Api/Maroc.Api.csproj" --configuration Release --no-restore
        dotnet build "MarocMarketplace/Maroc.Core/Maroc.Core.csproj" --configuration Release --no-restore
        dotnet build "MarocMarketplace/Maroc.Infrastructure/Maroc.Infrastructure.csproj" --configuration Release --no-restore

    - name: Run .NET tests
      run: |
        dotnet test "MarocMarketplace/Maroc.Api/Maroc.Api.csproj" --no-restore --verbosity normal
        dotnet test "MarocMarketplace/Maroc.Core/Maroc.Core.csproj" --no-restore --verbosity normal
        dotnet test "MarocMarketplace/Maroc.Infrastructure/Maroc.Infrastructure.csproj" --no-restore --verbosity normal
